### ISSUE TITLE
Pin CacheControl version

### ISSUE THREAD

**Issue by npavlovikj** [conda-forge/cwltool-feedstock#11]
`cwltool` supports `CacheControl<0.12,>=0.11.7`. However, some of its dependencies are pulling the newest 0.12.5 `cachecontrol` package, which makes `cwltool` complain and fail. 
I opened a PR with this change, https://github.com/conda-forge/cwltool-feedstock/pull/10.

**Comment by croth1** [comment]
@npavlovikj, argh that's nasty. I think the source of the problem are broken schema-salad packages which do not pin cachecontrol properly (as reported and fixed here: https://github.com/conda-forge/schema-salad-feedstock/pull/4)

Can you try installing the right schema-salad package by
```
conda install schema-salad=3.0.20181206233650=<py-version>_1001
```

Where `<py-version>` can be `py27`, `py36` or `py37`.

For me `conda install schema-salad=3.0.20181206233650=py36_1002` forced the downgrade of CacheControl.
 
I asked core to mark the faulty builds as broken.

**Comment by croth1** [comment]
@conda-forge/core would it be possible to mark following builds/packages as broken?

schema-salad-3.0.20181129082112_*_1000
schema-salad-3.0.20181206233650_*_1000
schema-salad-3.0.20181206233650_*_1001

**Comment by ocefpaf** [comment]
Done. Can you please check if I got it correctly?

**Comment by croth1** [comment]
@ocefpaf looks perfect, thanks 👍
