### ISSUE TITLE
@conda-forge-admin, please add noarch: python

### ISSUE THREAD

**Issue by xhochy** [conda-forge/cwltool-feedstock#4]
@conda-forge-admin, please add noarch: python

**Comment by croth1** [comment]
We discussed no-arching cwltool here: https://github.com/conda-forge/staged-recipes/pull/7214

Back then, I was not sure whether this recipe can be turned noarch. Can you check whether my comments there made sense?

**Comment by xhochy** [comment]
They still seem valid, I have a look at what's wrong with #3 then. Can you close #5, please?
